const esrs = [
  { group: 'E', label: 'ESRS E1-1: Climate change adaptation', subValue: 'E1-1' },
  { group: 'E', label: 'ESRS E1-2: Climate change mitigation', subValue: 'E1-2' },
  { group: 'E', label: 'ESRS E1-3: Energy', subValue: 'E1-3' },
  { group: 'E', label: 'ESRS E2-1: Pollution of air', subValue: 'E2-1' },
  { group: 'E', label: 'ESRS E2-2: Pollution of water', subValue: 'E2-2' },
  { group: 'E', label: 'ESRS E2-3: Pollution of soil', subValue: 'E2-3' },
  { group: 'E', label: 'ESRS E2-4: Pollution of living organisms and food resources', subValue: 'E2-4' },
  { group: 'E', label: 'ESRS E2-5: Substances of concern', subValue: 'E2-5' },
  { group: 'E', label: 'ESRS E2-6: Substances of very high concern', subValue: 'E2-6' },
  { group: 'E', label: 'ESRS E2-7: Microplastics', subValue: 'E2-7' },
  { group: 'E', label: 'ESRS E3-1: Water consumption', subValue: 'E3-1' },
  { group: 'E', label: 'ESRS E3-2: Water withdrawals', subValue: 'E3-2' },
  { group: 'E', label: 'ESRS E3-3: Water discharges', subValue: 'E3-3' },
  { group: 'E', label: 'ESRS E3-4: Water discharges to water bodies and oceans', subValue: 'E3-4' },
  { group: 'E', label: 'ESRS E3-5: Extraction and use of marine resources', subValue: 'E3-5' },
  { group: 'E', label: 'ESRS E4-1: Climate change', subValue: 'E4-1' },
  { group: 'E', label: 'ESRS E4-2: Land-use change', subValue: 'E4-2' },
  { group: 'E', label: 'ESRS E4-3: Fresh water-use change', subValue: 'E4-3' },
  { group: 'E', label: 'ESRS E4-4: Sea-use change', subValue: 'E4-4' },
  { group: 'E', label: 'ESRS E4-5: Direct exploitation', subValue: 'E4-5' },
  { group: 'E', label: 'ESRS E4-6: Invasive alien species', subValue: 'E4-6' },
  { group: 'E', label: 'ESRS E4-7: Pollution', subValue: 'E4-7' },
  { group: 'E', label: 'ESRS E4-8: Others', subValue: 'E4-8' },
  { group: 'E', label: 'ESRS E4-9: Impacts on the state of the species', subValue: 'E4-9' },
  { group: 'E', label: 'ESRS E4-10: Land degredation', subValue: 'E4-10' },
  { group: 'E', label: 'ESRS E4-11: Desertification', subValue: 'E4-11' },
  { group: 'E', label: 'ESRS E4-12: Soil sealing', subValue: 'E4-12' },
  { group: 'E', label: 'ESRS E4-13: Impacts on and dependencies of ecosystem services', subValue: 'E4-13' },
  { group: 'E', label: 'ESRS E5-1: Resource inflows, including resource use', subValue: 'E5-1' },
  { group: 'E', label: 'ESRS E5-2: Resource outflows related to products and services', subValue: 'E5-2' },
  { group: 'E', label: 'ESRS E5-3: Waste', subValue: 'E5-3' },
  { group: 'S', label: 'ESRS S1-1: Secure employment', subValue: 'S1-1' },
  { group: 'S', label: 'ESRS S1-2: Working time', subValue: 'S1-2' },
  { group: 'S', label: 'ESRS S1-3: Adequate wages', subValue: 'S1-3' },
  { group: 'S', label: 'ESRS S1-4: Social dialogue', subValue: 'S1-4' },
  { group: 'S', label: 'ESRS S1-5: Freedom of association and rights of workers', subValue: 'S1-5' },
  { group: 'S', label: 'ESRS S1-6: Collective bargaining', subValue: 'S1-6' },
  { group: 'S', label: 'ESRS S1-7: Work-life balance', subValue: 'S1-7' },
  { group: 'S', label: 'ESRS S1-8: Health and safety', subValue: 'S1-8' },
  { group: 'S', label: 'ESRS S1-9: Gender equality and equal pay for work of equal value', subValue: 'S1-9' },
  { group: 'S', label: 'ESRS S1-10: Training and skills development', subValue: 'S1-10' },
  { group: 'S', label: 'ESRS S1-11: Employment and inclusion of persons with disabilities', subValue: 'S1-11' },
  { group: 'S', label: 'ESRS S1-12: Measures against violence and harassment in the workplace', subValue: 'S1-12' },
  { group: 'S', label: 'ESRS S1-13: Diversity', subValue: 'S1-13' },
  { group: 'S', label: 'ESRS S1-14: Child labor', subValue: 'S1-14' },
  { group: 'S', label: 'ESRS S1-15: Forced labor', subValue: 'S1-15' },
  { group: 'S', label: 'ESRS S1-16: Adequate housing', subValue: 'S1-16' },
  { group: 'S', label: 'ESRS S1-17: Privacy', subValue: 'S1-17' },
  { group: 'S', label: 'ESRS S2-1: Secure employment', subValue: 'S2-1' },
  { group: 'S', label: 'ESRS S2-2: Working hours', subValue: 'S2-2' },
  { group: 'S', label: 'ESRS S2-3: Adequate wages', subValue: 'S2-3' },
  { group: 'S', label: 'ESRS S2-4: Social dialogue', subValue: 'S2-4' },
  { group: 'S', label: 'ESRS S2-5: Freedom of association, the existence of works councils', subValue: 'S2-5' },
  { group: 'S', label: 'ESRS S2-6: Collective bargaining', subValue: 'S2-6' },
  { group: 'S', label: 'ESRS S2-7: Work-life balance', subValue: 'S2-7' },
  { group: 'S', label: 'ESRS S2-8: Health and safety', subValue: 'S2-8' },
  { group: 'S', label: 'ESRS S2-9: Gender equality and equal pay for work of equal value', subValue: 'S2-9' },
  { group: 'S', label: 'ESRS S2-10: Training and skills development', subValue: 'S2-10' },
  { group: 'S', label: 'ESRS S2-11: Employment and inclusion of people with disabilities', subValue: 'S2-11' },
  { group: 'S', label: 'ESRS S2-12: Measures against violence and harassment in the workplace', subValue: 'S2-12' },
  { group: 'S', label: 'ESRS S2-13: Diversity', subValue: 'S2-13' },
  { group: 'S', label: 'ESRS S2-14: Child labor', subValue: 'S2-14' },
  { group: 'S', label: 'ESRS S2-15: Forced labor', subValue: 'S2-15' },
  { group: 'S', label: 'ESRS S2-16: Adequate housing', subValue: 'S2-16' },
  { group: 'S', label: 'ESRS S2-17: Water and sanitation', subValue: 'S2-17' },
  { group: 'S', label: 'ESRS S2-18: Privacy', subValue: 'S2-18' },
  { group: 'S', label: 'ESRS S3-1: Adequate housing', subValue: 'S3-1' },
  { group: 'S', label: 'ESRS S3-2: Adequate food', subValue: 'S3-2' },
  { group: 'S', label: 'ESRS S3-3: Water and sanitation', subValue: 'S3-3' },
  { group: 'S', label: 'ESRS S3-4: Land-related impacts', subValue: 'S3-4' },
  { group: 'S', label: 'ESRS S3-5: Security-related impacts', subValue: 'S3-5' },
  { group: 'S', label: 'ESRS S3-6: Freedom of expression', subValue: 'S3-6' },
  { group: 'S', label: 'ESRS S3-7: Freedom of assembly', subValue: 'S3-7' },
  { group: 'S', label: 'ESRS S3-8: Impacts on human rights defenders', subValue: 'S3-8' },
  { group: 'S', label: 'ESRS S3-9: Free, prior and informed consent', subValue: 'S3-9' },
  { group: 'S', label: 'ESRS S3-10: Self-determination', subValue: 'S3-10' },
  { group: 'S', label: 'ESRS S3-11: Cutural rights', subValue: 'S3-11' },
  { group: 'S', label: 'ESRS S4-1: Privacy', subValue: 'S4-1' },
  { group: 'S', label: 'ESRS S4-2: Freedom of expression', subValue: 'S4-2' },
  { group: 'S', label: 'ESRS S4-3: Access to quality information', subValue: 'S4-3' },
  { group: 'S', label: 'ESRS S4-4: Health and safety', subValue: 'S4-4' },
  { group: 'S', label: 'ESRS S4-5: Security of a person', subValue: 'S4-5' },
  { group: 'S', label: 'ESRS S4-6: Protection of children', subValue: 'S4-6' },
  { group: 'S', label: 'ESRS S4-7: Non-discrimination', subValue: 'S4-7' },
  { group: 'S', label: 'ESRS S4-8: Access to products and services', subValue: 'S4-8' },
  { group: 'S', label: 'ESRS S4-9: Responsible marketing practices', subValue: 'S4-9' },
  { group: 'G', label: 'ESRS G1-1: Corporate culture', subValue: 'G1-1' },
  { group: 'G', label: 'ESRS G1-2: Protection of whistleblowers', subValue: 'G1-2' },
  { group: 'G', label: 'ESRS G1-3: Animal welfare', subValue: 'G1-3' },
  { group: 'G', label: 'ESRS G1-4: Political engagement', subValue: 'G1-4' },
  { group: 'G', label: 'ESRS G1-5: Management of relationships with suppliers', subValue: 'G1-5' },
  { group: 'G', label: 'ESRS G1-6: Corruption and bribery', subValue: 'G1-6' },
  { group: 'E', label: 'ESRS E: Other environment', subValue: 'E' },
  { group: 'S', label: 'ESRS S: Other social', subValue: 'S' },
  { group: 'G', label: 'ESRS G: Other governance', subValue: 'G' },
];

export const ESRSUtils = {
  getGroup: (targetSubValue: string) => {
    const esrsItem = esrs.find(({ subValue }) => subValue === targetSubValue);
    if (!esrsItem) throw new Error('Invalid ESRS sub value');
    return esrsItem.group;
  },
  getLabel: (targetSubValue: string) => {
    const esrsItem = esrs.find(({ subValue }) => subValue === targetSubValue);
    if (!esrsItem) throw new Error('Invalid ESRS sub value');
    return esrsItem.label;
  },
  getGroupFromLabel: (targetLabel: string) => {
    const esrsItem = esrs.find(({ label }) => label === targetLabel);
    if (!esrsItem) throw new Error('Invalid ESRS sub value');
    return esrsItem.group;
  },
  getSubValueFromLabel: (targetLabel: string) => {
    const esrsItem = esrs.find(({ label }) => label === targetLabel);
    if (!esrsItem) throw new Error('Invalid ESRS sub value');
    return esrsItem.subValue;
  },
};
